export const DEFAULT_COMPANY_DETAILS_PROMPT = `Identify the company from its name and website when available. Return only high-level facts useful while evaluating a job opportunity. Keep the description concise, factual, and neutral. Do not add marketing language or speculate when the company cannot be identified confidently.`;

export const DEFAULT_RESUME_REVIEW_PROMPT = `Evaluate whether the current resume is already a reasonable fit for the role. A resume does not need to be perfect. Recommend a new resume variation only when there is a material gap that could meaningfully weaken the application and the supplied verified career evidence can address that gap. Do not recommend changes for minor keyword differences, stylistic polish, cosmetic reordering, marginal optimization, or wording preferences. When the resume is already a good fit, explicitly say so and recommend no changes.`;

export const DEFAULT_COVER_LETTER_PROMPT = `Write a concise, role-specific cover letter using only verified facts. Follow this structure when the available information supports it: candidate name on the first line; contact line on the second line; a blank line; hiring team or recipient; Re: role title and job ID when known; greeting; several short evidence-based paragraphs separated by blank lines; a location or work-arrangement sentence when relevant; brief thank-you; and sign-off. Match the restraint and directness of the saved cover-letter format. Avoid generic praise, inflated language, unsupported claims, and repetition of the resume.`;

export const DEFAULT_CAREER_ENTRY_SUMMARY_PROMPT = `Summarize one verified career entry for later resume matching. Keep the summary factual, compact, and focused on scope, skills, technologies, responsibilities, and measurable outcomes that are explicitly present in the entry. Do not add claims or infer missing details.`;

export const DEFAULT_CAREER_PROFILE_PROMPT = `Create a concise overall career profile from the verified Career Library entries. Emphasize role positioning, domains, strengths, delivery scope, leadership, and technical fluency supported by the entries. Do not invent facts, metrics, credentials, or experience.`;

export const DEFAULT_CAREER_ENTRY_DESCRIPTION_PROMPT = `Create or refine the detailed description for one verified Career Library entry. Use only facts already present in the entry. Organize the description so it captures scope, responsibilities, decisions, technologies, collaboration, and outcomes when those facts are available. If a detailed description already exists, improve clarity and completeness without changing meaning or inventing details.`;
